version: "3"

services:

  go-server:
    build: go-server
    container_name: go-server
    ports:
      - "5000:5000"

  web-server:
    build: web-server
    container_name: web-server
    ports:
      - "8080:8080"
