version: "3"

services:

  chat-server:
    build: chat-server
    container_name: chat-server
    depends_on:
      - mongoDB
    ports:
      - "4000:4000"

  web-server:
    build: web-server
    container_name: web-server
    depends_on:
      - chat-server
    ports:
      - "3000:3000"
    volumes:
      - ./web-server/logs:/app/logs

  mongoDB:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
