services:

  chat-server:
    build: chat-server
    container_name: chat-server
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - ./chat-server/logs:/app/logs

  web-server:
    build: web-server
    container_name: web-server
    depends_on:
      - chat-server
    ports:
      - "3000:3000"
    volumes:
      - ./web-server/logs:/app/logs

  mongo:
    image: mongo:7.0.11
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      -  ~/mongoDB:/data/db
